# Compliance Batch 2: Mappings 21-40

COMPLIANCE_BATCH_2 = {
    "ecr_image_scan_on_push": {
        "mitre_mapping": "T1525 (Implant Internal Image)",
        "compliance": "CIS Docker 4.5 | NIST 800-53 RA-5 | PCI-DSS 6.2",
        "nist_controls": "RA-5, SI-3",
        "pci_controls": "PCI-DSS 6.2",
        "iso_controls": "ISO 27001 A.12.6.1",
    },
    "ecs_task_definition_container_readonly_root_filesystem": {
        "mitre_mapping": "T1611 (Escape to Host)",
        "compliance": "CIS Docker 5.12 | NIST 800-53 CM-7 | PCI-DSS 2.2",
        "nist_controls": "CM-7, AC-6",
        "pci_controls": "PCI-DSS 2.2",
        "iso_controls": "ISO 27001 A.9.4.5",
    },
    "eks_control_plane_logging_all_types_enabled": {
        "mitre_mapping": "T1562.008 (Impair Defenses: Disable Cloud Logs)",
        "compliance": "CIS EKS 3.2.1 | NIST 800-53 AU-2 | PCI-DSS 10.2.1",
        "nist_controls": "AU-2, AU-12",
        "pci_controls": "PCI-DSS 10.2.1",
        "iso_controls": "ISO 27001 A.12.4.1",
    },
    "elb_internet_facing": {
        "mitre_mapping": "T1190 (Exploit Public-Facing Application)",
        "compliance": "AWS FSBP ELB.2 | NIST 800-53 SC-7 | PCI-DSS 1.3.1",
        "nist_controls": "SC-7, AC-4",
        "pci_controls": "PCI-DSS 1.3.1",
        "iso_controls": "ISO 27001 A.13.1.3",
    },
    "elb_logging_enabled": {
        "mitre_mapping": "T1070.004 (Indicator Removal: File Deletion)",
        "compliance": "AWS FSBP ELB.1 | NIST 800-53 AU-2 | PCI-DSS 10.2.1",
        "nist_controls": "AU-2, AU-3",
        "pci_controls": "PCI-DSS 10.2.1",
        "iso_controls": "ISO 27001 A.12.4.1",
    },
    "elb_ssl_listeners": {
        "mitre_mapping": "T1040 (Network Sniffing)",
        "compliance": "AWS FSBP ELB.4 | NIST 800-53 SC-8 | PCI-DSS 4.1",
        "nist_controls": "SC-8, SC-13",
        "pci_controls": "PCI-DSS 4.1",
        "iso_controls": "ISO 27001 A.13.1.1",
    },
    "elbv2_insecure_ssl_ciphers": {
        "mitre_mapping": "T1040 (Network Sniffing)",
        "compliance": "AWS FSBP ELB.5 | NIST 800-53 SC-8 | PCI-DSS 4.1",
        "nist_controls": "SC-8, SC-13",
        "pci_controls": "PCI-DSS 4.1",
        "iso_controls": "ISO 27001 A.14.1.2",
    },
    "es_domain_encryption_at_rest_enabled": {
        "mitre_mapping": "T1213 (Data from Information Repositories)",
        "compliance": "AWS FSBP ES.1 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "guardduty_is_enabled": {
        "mitre_mapping": "T1562 (Impair Defenses)",
        "compliance": "AWS FSBP GuardDuty.1 | NIST 800-53 SI-4 | SOC 2 CC7.2",
        "nist_controls": "SI-4, IR-4",
        "pci_controls": "PCI-DSS 10.6.1",
        "iso_controls": "ISO 27001 A.12.4.1",
    },
    "guardduty_no_high_severity_findings": {
        "mitre_mapping": "T1562 (Impair Defenses)",
        "compliance": "AWS FSBP GuardDuty.2 | NIST 800-53 SI-4 | SOC 2 CC7.2",
        "nist_controls": "SI-4, IR-4",
        "pci_controls": "PCI-DSS 10.6",
        "iso_controls": "ISO 27001 A.16.1.1",
    },
    "iam_inline_policy_no_administrative_privileges": {
        "mitre_mapping": "T1098.003 (Account Manipulation: Additional Cloud Roles)",
        "compliance": "CIS AWS 1.16 | NIST 800-53 AC-6 | PCI-DSS 7.1.2",
        "nist_controls": "AC-6, AC-2",
        "pci_controls": "PCI-DSS 7.1.2",
        "iso_controls": "ISO 27001 A.9.2.3",
    },
    "iam_password_policy": {
        "mitre_mapping": "T1110 (Brute Force)",
        "compliance": "CIS AWS 1.8-1.11 | NIST 800-53 IA-5(1) | PCI-DSS 8.2.3",
        "nist_controls": "IA-5(1), AC-2",
        "pci_controls": "PCI-DSS 8.2.3",
        "iso_controls": "ISO 27001 A.9.4.3",
    },
    "iam_password_policy_reuse_24": {
        "mitre_mapping": "T1110 (Brute Force)",
        "compliance": "CIS AWS 1.10 | NIST 800-53 IA-5(1) | PCI-DSS 8.2.5",
        "nist_controls": "IA-5(1)",
        "pci_controls": "PCI-DSS 8.2.5",
        "iso_controls": "ISO 27001 A.9.4.3",
    },
    "iam_policy_admin_access": {
        "mitre_mapping": "T1484 (Domain Policy Modification)",
        "compliance": "CIS AWS 1.16 | NIST 800-53 AC-6 | PCI-DSS 7.1",
        "nist_controls": "AC-6, AC-2",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.2.3",
    },
    "iam_role_privilege_escalation": {
        "mitre_mapping": "T1098 (Account Manipulation)",
        "compliance": "AWS FSBP IAM.4 | NIST 800-53 AC-6 | PCI-DSS 7.1.2",
        "nist_controls": "AC-6, AC-2",
        "pci_controls": "PCI-DSS 7.1.2",
        "iso_controls": "ISO 27001 A.9.2.3",
    },
    "iam_root_access_key": {
        "mitre_mapping": "T1078.004 (Valid Accounts: Cloud Accounts)",
        "compliance": "CIS AWS 1.4 | NIST 800-53 IA-2 | PCI-DSS 8.1.1 | SOC 2 CC6.1",
        "nist_controls": "IA-2, AC-6",
        "pci_controls": "PCI-DSS 8.1.1",
        "iso_controls": "ISO 27001 A.9.2.1",
    },
    "iam_root_hardware_mfa_enabled": {
        "mitre_mapping": "T1556.006 (Modify Authentication Mechanism: Multi-Factor Authentication)",
        "compliance": "CIS AWS 1.14 | NIST 800-53 IA-2(1) | PCI-DSS 8.3 | SOC 2 CC6.1",
        "nist_controls": "IA-2(1), IA-5(1)",
        "pci_controls": "PCI-DSS 8.3",
        "iso_controls": "ISO 27001 A.9.4.2",
    },
    "iam_user_console_access_mfa": {
        "mitre_mapping": "T1078.004 (Valid Accounts: Cloud Accounts)",
        "compliance": "CIS AWS 1.2 | NIST 800-53 IA-2(1) | PCI-DSS 8.3 | SOC 2 CC6.1",
        "nist_controls": "IA-2(1)",
        "pci_controls": "PCI-DSS 8.3",
        "iso_controls": "ISO 27001 A.9.4.2",
    },
    "iam_user_unused_credentials_90_days": {
        "mitre_mapping": "T1078.004 (Valid Accounts: Cloud Accounts)",
        "compliance": "CIS AWS 1.3 | NIST 800-53 AC-2 | PCI-DSS 8.1.4",
        "nist_controls": "AC-2, IA-4",
        "pci_controls": "PCI-DSS 8.1.4",
        "iso_controls": "ISO 27001 A.9.2.6",
    },
    "lambda_function_public_access": {
        "mitre_mapping": "T1190 (Exploit Public-Facing Application)",
        "compliance": "AWS FSBP Lambda.1 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, AC-6",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
}
