# Compliance Batch 3: Mappings 41-60

COMPLIANCE_BATCH_3 = {
    "lambda_function_url_public": {
        "mitre_mapping": "T1190 (Exploit Public-Facing Application)",
        "compliance": "AWS FSBP Lambda.2 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, SC-7",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "lambda_function_vpc_enabled": {
        "mitre_mapping": "T1133 (External Remote Services)",
        "compliance": "AWS FSBP Lambda.3 | NIST 800-53 SC-7 | PCI-DSS 1.3",
        "nist_controls": "SC-7, AC-4",
        "pci_controls": "PCI-DSS 1.3",
        "iso_controls": "ISO 27001 A.13.1.3",
    },
    "opensearch_service_domains_encryption_at_rest_enabled": {
        "mitre_mapping": "T1213 (Data from Information Repositories)",
        "compliance": "AWS FSBP OpenSearch.1 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "redshift_cluster_encryption": {
        "mitre_mapping": "T1213 (Data from Information Repositories)",
        "compliance": "AWS FSBP Redshift.2 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "redshift_cluster_public_access": {
        "mitre_mapping": "T1133 (External Remote Services)",
        "compliance": "AWS FSBP Redshift.1 | NIST 800-53 SC-7 | PCI-DSS 1.3.1",
        "nist_controls": "SC-7, AC-3",
        "pci_controls": "PCI-DSS 1.3.1",
        "iso_controls": "ISO 27001 A.13.1.1",
    },
    "rds_snapshots_public_access": {
        "mitre_mapping": "T1530 (Data from Cloud Storage Object)",
        "compliance": "AWS FSBP RDS.1 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, AC-6",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "rds_automated_backups": {
        "mitre_mapping": "T1485 (Data Destruction)",
        "compliance": "AWS FSBP RDS.4 | NIST 800-53 CP-9 | PCI-DSS 3.4",
        "nist_controls": "CP-9, SI-12",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.12.3.1",
    },
    "s3_account_level_public_access_blocks": {
        "mitre_mapping": "T1530 (Data from Cloud Storage Object)",
        "compliance": "AWS FSBP S3.1 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, AC-6",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "s3_bucket_level_public_access_block": {
        "mitre_mapping": "T1530 (Data from Cloud Storage Object)",
        "compliance": "CIS AWS 2.1.5 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, AC-6",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "s3_bucket_mfa_delete": {
        "mitre_mapping": "T1485 (Data Destruction)",
        "compliance": "CIS AWS 2.1.3 | NIST 800-53 SC-28 | SOC 2 CC6.1",
        "nist_controls": "SC-28, IA-2(1)",
        "pci_controls": "PCI-DSS 8.3",
        "iso_controls": "ISO 27001 A.12.3.1",
    },
    "s3_bucket_no_lifecycle_configuration": {
        "mitre_mapping": "T1078 (Valid Accounts)",
        "compliance": "AWS Best Practices | NIST 800-53 CM-8",
        "nist_controls": "CM-8, SA-3",
        "pci_controls": "PCI-DSS 2.2",
        "iso_controls": "ISO 27001 A.12.5.1",
    },
    "s3_bucket_server_side_encryption_enabled": {
        "mitre_mapping": "T1213 (Data from Information Repositories)",
        "compliance": "CIS AWS 2.1.1 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "secretsmanager_rotation_enabled": {
        "mitre_mapping": "T1552.004 (Unsecured Credentials: Private Keys)",
        "compliance": "AWS FSBP SecretsManager.1 | NIST 800-53 IA-5(1) | PCI-DSS 8.2.4",
        "nist_controls": "IA-5(1), SC-12",
        "pci_controls": "PCI-DSS 8.2.4",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "secretsmanager_secret_not_used": {
        "mitre_mapping": "T1552 (Unsecured Credentials)",
        "compliance": "AWS Best Practices | NIST 800-53 CM-8",
        "nist_controls": "CM-8, AC-2",
        "pci_controls": "PCI-DSS 8.1.4",
        "iso_controls": "ISO 27001 A.9.2.6",
    },
    "ssm_document_secrets_in_variables": {
        "mitre_mapping": "T1552.001 (Unsecured Credentials: Credentials In Files)",
        "compliance": "AWS FSBP SSM.1 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, IA-5",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.2",
    },
    "ssm_parameter_encryption": {
        "mitre_mapping": "T1552.001 (Unsecured Credentials: Credentials In Files)",
        "compliance": "AWS FSBP SSM.2 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.2",
    },
    "vpc_default_security_group_restricts_all_traffic": {
        "mitre_mapping": "T1046 (Network Service Discovery)",
        "compliance": "CIS AWS 5.4 | NIST 800-53 SC-7 | PCI-DSS 1.2.1",
        "nist_controls": "SC-7, AC-4",
        "pci_controls": "PCI-DSS 1.2.1",
        "iso_controls": "ISO 27001 A.13.1.1",
    },
    "vpc_endpoint_exposed": {
        "mitre_mapping": "T1133 (External Remote Services)",
        "compliance": "AWS FSBP VPC.7 | NIST 800-53 SC-7 | PCI-DSS 1.3",
        "nist_controls": "SC-7, AC-3",
        "pci_controls": "PCI-DSS 1.3",
        "iso_controls": "ISO 27001 A.13.1.3",
    },
    "kms_key_rotation_enabled": {
        "mitre_mapping": "T1552 (Unsecured Credentials)",
        "compliance": "CIS AWS 3.8 | NIST 800-53 SC-12 | PCI-DSS 3.6.4",
        "nist_controls": "SC-12, SC-13",
        "pci_controls": "PCI-DSS 3.6.4",
        "iso_controls": "ISO 27001 A.10.1.2",
    },
    "iam_password_policy_minimum_length": {
        "mitre_mapping": "T1110.001 (Brute Force: Password Guessing)",
        "compliance": "CIS AWS 1.8 | NIST 800-53 IA-5(1) | PCI-DSS 8.2.3",
        "nist_controls": "IA-5(1)",
        "pci_controls": "PCI-DSS 8.2.3",
        "iso_controls": "ISO 27001 A.9.4.3",
    },
}
