# Compliance Batch 4: Final mappings 61-73

COMPLIANCE_BATCH_4 = {
    "s3_bucket_default_encryption": {
        "mitre_mapping": "T1213 (Data from Information Repositories)",
        "compliance": "CIS AWS 2.1.1 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "vpc_nat_gateway_unused": {
        "mitre_mapping": "T1078 (Valid Accounts)",
        "compliance": "AWS Best Practices | NIST 800-53 CM-8",
        "nist_controls": "CM-8",
        "pci_controls": "PCI-DSS 2.2",
        "iso_controls": "ISO 27001 A.12.5.1",
    },
    "ec2_stopped_instance": {
        "mitre_mapping": "T1078 (Valid Accounts)",
        "compliance": "AWS Best Practices | NIST 800-53 CM-8",
        "nist_controls": "CM-8, SA-3",
        "pci_controls": "PCI-DSS 2.2",
        "iso_controls": "ISO 27001 A.12.5.1",
    },
    "elb_with_no_instances": {
        "mitre_mapping": "T1078 (Valid Accounts)",
        "compliance": "AWS Best Practices | NIST 800-53 CM-8",
        "nist_controls": "CM-8",
        "pci_controls": "PCI-DSS 2.2",
        "iso_controls": "ISO 27001 A.12.5.1",
    },
    "secretsmanager_unused_secret": {
        "mitre_mapping": "T1552 (Unsecured Credentials)",
        "compliance": "AWS Best Practices | NIST 800-53 CM-8",
        "nist_controls": "CM-8, AC-2",
        "pci_controls": "PCI-DSS 8.1.4",
        "iso_controls": "ISO 27001 A.9.2.6",
    },
    "cloudwatch_log_group_retention_policy_specific_days_enabled": {
        "mitre_mapping": "T1070.004 (Indicator Removal: File Deletion)",
        "compliance": "AWS FSBP CloudWatch.2 | NIST 800-53 AU-11 | PCI-DSS 10.7",
        "nist_controls": "AU-11, SI-12",
        "pci_controls": "PCI-DSS 10.7",
        "iso_controls": "ISO 27001 A.12.4.3",
    },
    "ec2_ebs_volume_encryption": {
        "mitre_mapping": "T1005 (Data from Local System)",
        "compliance": "AWS FSBP EC2.7 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "rdb_instance_storage_encrypted": {
        "mitre_mapping": "T1005 (Data from Local System)",
        "compliance": "AWS FSBP RDS.3 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "vpc_flow_logs_enabled": {
        "mitre_mapping": "T1562.001 (Impair Defenses: Disable or Modify Tools)",
        "compliance": "AWS FSBP VPC.1 | NIST 800-53 AU-2 | PCI-DSS 10.2.1",
        "nist_controls": "AU-2, SI-4",
        "pci_controls": "PCI-DSS 10.2.1",
        "iso_controls": "ISO 27001 A.12.4.1",
    },
    "lambda_function_restrict_public_access": {
        "mitre_mapping": "T1190 (Exploit Public-Facing Application)",
        "compliance": "AWS FSBP Lambda.1 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, AC-6",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "iam_password_policy_minimum_length_14": {
        "mitre_mapping": "T1110.001 (Brute Force: Password Guessing)",
        "compliance": "CIS AWS 1.8 | NIST 800-53 IA-5(1) | PCI-DSS 8.2.3",
        "nist_controls": "IA-5(1), AC-2",
        "pci_controls": "PCI-DSS 8.2.3",
        "iso_controls": "ISO 27001 A.9.4.3",
    },
    "vpc_network_acl_unrestricted": {
        "mitre_mapping": "T1046 (Network Service Discovery)",
        "compliance": "CIS AWS 5.1 | NIST 800-53 SC-7 | PCI-DSS 1.2.1",
        "nist_controls": "SC-7, AC-4",
        "pci_controls": "PCI-DSS 1.2.1",
        "iso_controls": "ISO 27001 A.13.1.1",
    },
    "_default": {
        "mitre_mapping": "T1078 (Valid Accounts / Configuration Variance)",
        "compliance": "CIS AWS Foundations Framework Checklist",
        "nist_controls": "AC-2, AC-6",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.2.1",
    },
}
