# Compliance Batch 1: First 20 mappings

COMPLIANCE_BATCH_1 = {
    "acm_certificates_expiration_check": {
        "mitre_mapping": "T1588.004 (Obtain Capabilities: Digital Certificates)",
        "compliance": "AWS FSBP ACM.1 | NIST 800-53 SC-12 | PCI-DSS 4.1",
        "nist_controls": "SC-12, IA-5",
        "pci_controls": "PCI-DSS 4.1",
        "iso_controls": "ISO 27001 A.14.1.3",
    },
    "apigateway_client_certificate_enabled": {
        "mitre_mapping": "T1071.001 (Application Layer Protocol: Web Protocols)",
        "compliance": "AWS FSBP APIGateway.3 | NIST 800-53 SC-8 | PCI-DSS 4.1",
        "nist_controls": "SC-8, SC-13",
        "pci_controls": "PCI-DSS 4.1",
        "iso_controls": "ISO 27001 A.13.1.1",
    },
    "backup_plans_exist": {
        "mitre_mapping": "T1485 (Data Destruction)",
        "compliance": "AWS FSBP Backup.1 | NIST 800-53 CP-9 | PCI-DSS 3.4 | SOC 2 CC5.1",
        "nist_controls": "CP-9, SI-12",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.12.3.1",
    },
    "backup_recovery_point_encrypted": {
        "mitre_mapping": "T1485 (Data Destruction)",
        "compliance": "AWS FSBP Backup.2 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, CP-9",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "backup_recovery_point_manual_deletion_disabled": {
        "mitre_mapping": "T1485 (Data Destruction)",
        "compliance": "AWS FSBP Backup.4 | NIST 800-53 CP-9 | SOC 2 CC5.1",
        "nist_controls": "CP-9, CM-3",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.12.3.1",
    },
    "cloudtrail_cloudwatch_logging_enabled": {
        "mitre_mapping": "T1562.008 (Impair Defenses: Disable Cloud Logs)",
        "compliance": "CIS AWS 3.4 | NIST 800-53 AU-6 | PCI-DSS 10.6.1 | SOC 2 CC7.2",
        "nist_controls": "AU-6, SI-4",
        "pci_controls": "PCI-DSS 10.6.1",
        "iso_controls": "ISO 27001 A.12.4.1",
    },
    "cloudtrail_kms_encryption_enabled": {
        "mitre_mapping": "T1565.001 (Data Manipulation: Stored Data Manipulation)",
        "compliance": "CIS AWS 3.7 | NIST 800-53 AU-9 | PCI-DSS 10.5 | SOC 2 CC7.2",
        "nist_controls": "AU-9, SC-28",
        "pci_controls": "PCI-DSS 10.5",
        "iso_controls": "ISO 27001 A.12.4.2",
    },
    "cloudtrail_logs_s3_bucket_access_logging_enabled": {
        "mitre_mapping": "T1070.004 (Indicator Removal: File Deletion)",
        "compliance": "CIS AWS 3.6 | NIST 800-53 AU-9 | PCI-DSS 10.5.4",
        "nist_controls": "AU-9, AU-11",
        "pci_controls": "PCI-DSS 10.5.4",
        "iso_controls": "ISO 27001 A.12.4.2",
    },
    "cloudwatch_alarm_actions": {
        "mitre_mapping": "T1562 (Impair Defenses)",
        "compliance": "AWS FSBP CloudWatch.1 | NIST 800-53 SI-4 | SOC 2 CC7.2",
        "nist_controls": "SI-4, IR-4",
        "pci_controls": "PCI-DSS 10.6",
        "iso_controls": "ISO 27001 A.12.4.1",
    },
    "cloudwatch_log_group_no_retention_policy": {
        "mitre_mapping": "T1070.004 (Indicator Removal: File Deletion)",
        "compliance": "AWS FSBP CloudWatch.2 | NIST 800-53 AU-11 | PCI-DSS 10.7",
        "nist_controls": "AU-11, SI-12",
        "pci_controls": "PCI-DSS 10.7",
        "iso_controls": "ISO 27001 A.12.4.3",
    },
    "config_enabled": {
        "mitre_mapping": "T1562 (Impair Defenses)",
        "compliance": "CIS AWS 3.5 | NIST 800-53 CM-8 | PCI-DSS 11.5 | SOC 2 CC7.2",
        "nist_controls": "CM-8, CM-3",
        "pci_controls": "PCI-DSS 11.5",
        "iso_controls": "ISO 27001 A.12.4.1",
    },
    "dynamodb_pitr_enabled": {
        "mitre_mapping": "T1485 (Data Destruction)",
        "compliance": "AWS FSBP DynamoDB.2 | NIST 800-53 CP-9 | PCI-DSS 3.4",
        "nist_controls": "CP-9, SI-12",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.12.3.1",
    },
    "ec2_ami_public": {
        "mitre_mapping": "T1525 (Implant Internal Image)",
        "compliance": "AWS FSBP EC2.1 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, CM-2",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "ec2_ebs_encryption": {
        "mitre_mapping": "T1005 (Data from Local System)",
        "compliance": "AWS FSBP EC2.7 | NIST 800-53 SC-28 | PCI-DSS 3.4",
        "nist_controls": "SC-28, SC-13",
        "pci_controls": "PCI-DSS 3.4",
        "iso_controls": "ISO 27001 A.10.1.1",
    },
    "ec2_ebs_public_snapshot": {
        "mitre_mapping": "T1530 (Data from Cloud Storage Object)",
        "compliance": "AWS FSBP EC2.2 | NIST 800-53 AC-3 | PCI-DSS 7.1",
        "nist_controls": "AC-3, AC-6",
        "pci_controls": "PCI-DSS 7.1",
        "iso_controls": "ISO 27001 A.9.4.1",
    },
    "ec2_elastic_ip_unassociated": {
        "mitre_mapping": "T1078 (Valid Accounts)",
        "compliance": "AWS FSBP EC2.4 | NIST 800-53 CM-8",
        "nist_controls": "CM-8",
        "pci_controls": "PCI-DSS 2.2",
        "iso_controls": "ISO 27001 A.12.5.1",
    },
    "ec2_instance_older_than_specific_days": {
        "mitre_mapping": "T1078 (Valid Accounts)",
        "compliance": "AWS Best Practices | NIST 800-53 CM-8 | SOC 2 CC7.2",
        "nist_controls": "CM-8, SA-3",
        "pci_controls": "PCI-DSS 2.2",
        "iso_controls": "ISO 27001 A.12.5.1",
    },
    "ec2_security_group_open_to_internet": {
        "mitre_mapping": "T1046 (Network Service Discovery)",
        "compliance": "CIS AWS 5.1 | NIST 800-53 SC-7 | PCI-DSS 1.3.1",
        "nist_controls": "SC-7, AC-4",
        "pci_controls": "PCI-DSS 1.3.1",
        "iso_controls": "ISO 27001 A.13.1.3",
    },
    "ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_3389": {
        "mitre_mapping": "T1021.001 (Remote Services: Remote Desktop Protocol)",
        "compliance": "CIS AWS 5.3 | NIST 800-53 AC-4 | PCI-DSS 1.3.1",
        "nist_controls": "AC-4, SC-7",
        "pci_controls": "PCI-DSS 1.3.1",
        "iso_controls": "ISO 27001 A.13.1.3",
    },
    "ec2_securitygroup_default_restrict_traffic": {
        "mitre_mapping": "T1046 (Network Service Discovery)",
        "compliance": "CIS AWS 5.4 | NIST 800-53 SC-7 | PCI-DSS 1.2.1",
        "nist_controls": "SC-7, AC-4",
        "pci_controls": "PCI-DSS 1.2.1",
        "iso_controls": "ISO 27001 A.13.1.1",
    },
}
